version: '1.0'

services:
  mysql8.0:
    image: mysql:8.0
    container_name: mysql8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=tempdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - ./my.cnf:/root/.my.cnf:ro
      - ./mysql8.0/conf.d:/etc/mysql/conf.d:ro
      - ./mysql8.0/logs:/var/log/mysql:rw
      - ./mysql8.0/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./auto-generate:/auto-generate:rw